config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home" # landing page (root_path)
  devise_for :users

  resources :users, only: [:show]
  resources :tasks do
    member do
      post 'start_task'
      patch 'accept_request'
      patch 'reject_request'
      patch 'done_task'
      post 'create_chatroom'
    end
    collection do
      get 'my_tasks' # Route for "my_tasks"
      get 'task_history', to: 'tasks#task_history' # Route for "task_history"
    end
  end

  resources :categories
  resources :chatrooms, only: [:index, :show, :new, :create] do
    resources :messages, only: :create
  end
end

app/models/task.rb
require 'open-uri'

class Task < ApplicationRecord
  belongs_to :category
  belongs_to :user
  belongs_to :requested_by, class_name: "User", foreign_key: "requested_by_id", optional: true
  has_many :chatrooms, dependent: :destroy
  has_many_attached :photos

  validates :task_status, inclusion: { in: %w[available requested in_work done] }, allow_nil: true
  validate :validate_photo_count

  before_validation :set_default_task_status, on: :create
  # The next 2 lines are for the geocoder gem
  geocoded_by :location
  after_validation :geocode, :check_geocode, if: :will_save_change_to_location?

  # The next method makes a double check on the geocoding (sometimes the first geocoding is not accurate)
  def check_geocode
    unless self.longitude && self.latitude
      url = "https://api.mapbox.com/geocoding/v5/mapbox.places/#{self.location.gsub(" ", "%20")}.json?&access_token=#{ENV["MAPBOX_API_KEY"]}"
      location_serialized = URI.open(url).read
      location = JSON.parse(location_serialized)
      coordinates = location["features"][0]["center"]
      self.longitude = coordinates[0]
      self.latitude = coordinates[1]
      self.save
    end
  end

  # Method to start a task request (only available if you are not the task owner)
  def start_request(user)
    puts "start_request method called"
    return false unless task_status == 'available'

    update(task_status: 'requested', requested_by: user)
  end

  # Method to accept a task request (only available if you are the task owner)
  def accept_request!
    return false unless task_status == 'requested'

    update(task_status: 'in_work')
  end

  # Method to mark a task as done (only available if you are the task owner)
  def reject_request!
    return false unless task_status == 'requested'

    update(requested_by_id: nil, task_status: 'available')
    true
  end

  # This makes sure that the current user can only create one chatroom for a task
  def user_can_create_chatroom(current_user)
    !Chatroom.exists?(task: self, user: current_user)
  end

  private

  def set_default_task_status
    self.task_status ||= "available"
  end

  # This makes sure that the user can only upload 4 photos for a task
  def validate_photo_count
    if photos.attached? && photos.length > 4
      errors.add(:photos, "can't exceed 4 photos")
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  # GET /tasks
  def index
    @sort_option = params[:sort]

    case @sort_option
    when 'newest'
      @tasks = Task.order(created_at: :desc)
    when 'oldest'
      @tasks = Task.order(created_at: :asc)
    when 'category'
      @categories = Category.all.order(:name) # :name is for gets the categories alphabeticly
    when 'highest_payment'
      @tasks = Task.order(price: :desc)
    else
      @tasks = Task.all
    end

    # This is needed for the blue dot in the navbar if there is a new message
    if user_signed_in?
      @chatrooms = Chatroom.joins(task: :user)
                           .joins("LEFT JOIN messages ON messages.chatroom_id = chatrooms.id")
                           .where("(tasks.user_id = :current_user_id OR chatrooms.user_id = :current_user_id)", current_user_id: current_user.id)
                           .group("chatrooms.id")
                           .order("MAX(messages.created_at) DESC NULLS LAST")
    else
      @chatrooms = [] # or whatever default behavior you want for users who are not signed in
    end

  end

  # GET /tasks/1
  def show
    @task = Task.find(params[:id])
    @user_can_create_chatroom = @task.user_can_create_chatroom(current_user)
    @task_status = @task.task_status || "default"
    @is_own_task = current_user == @task.user
    # Below is for the map
    if @task.latitude.present? && @task.longitude.present?
      @markers = [{
        lat: @task.latitude,
        lng: @task.longitude
      }]
    else
      @markers = []
    end
  end

  # GET /tasks/my_tasks
  def my_tasks
    @tasks = current_user.tasks
    @started_tasks = Task.where("(task_status = 'requested' AND requested_by_id = :user_id) OR task_status = 'in_work'", user_id: current_user.id)
    @requested_tasks = Task.where(task_status: "requested", user: current_user)
    @accepted_tasks = Task.joins(:user).where(users: { id: current_user.id }, task_status: "in_work")
    @done_tasks = Task.where(task_status: "done", user: current_user).or(Task.where(task_status: "done", requested_by: current_user))
  end

  # Method to start a task
  def start_task
    @task = Task.find(params[:id])
    return if @task.user == current_user

    @task.update(task_status: "requested", requested_by_id: current_user.id)

    redirect_to task_path, notice: "Request has been sent."
  end

  # Method to accept a task request
  def accept_request
    @task = Task.find(params[:id])

    if @task.accept_request!
      redirect_to my_tasks_tasks_path, notice: "Task request has been accepted."
    else
      redirect_to task_path(@task), alert: "Failed to accept the task request."
    end
  end

  # Method for the task owner to reject a task request
  def reject_request
    @task = Task.find(params[:id])

    if @task.reject_request!
      redirect_to my_tasks_tasks_path, notice: "Task request has been declined."
    else
      redirect_to task_path(@task), alert: "Failed to decline the task request."
    end
  end

  # Method for the task owner to mark a task as done
  def done_task
    @task = Task.find(params[:id])

    if current_user == @task.user && @task.update(task_status: "done")
      redirect_to my_tasks_tasks_path, notice: "Task has been marked as done."
    else
      redirect_to task_path(@task), alert: "Failed to mark the task as done."
    end
  end

  # GET /tasks/task_history
  def task_history
    @done_tasks = Task.where(task_status: 'done')
  end

  # GET /tasks/new
  def new
    if user_signed_in?
    @task = Task.new
      # This is needed for the blue dot in the navbar if there is a new message
      @chatrooms = Chatroom.joins(task: :user)
                          .joins("LEFT JOIN messages ON messages.chatroom_id = chatrooms.id")
                          .where("(tasks.user_id = :current_user_id OR chatrooms.user_id = :current_user_id)", current_user_id: current_user.id)
                          .group("chatrooms.id")
                          .order("MAX(messages.created_at) DESC NULLS LAST")
    else
      redirect_to new_user_session_path, alert: "You need to sign in to view messages."
    end
  end

  # Method to create a chatroom for a task
  def create_chatroom
    @task = Task.find(params[:id])
    @chatroom = Chatroom.new(task: @task, name: @task.name, user_id: current_user.id)

    if @chatroom.save
      redirect_to chatroom_path(@chatroom), notice: "Chatroom created successfully."
    else
      redirect_to task_path(@task), alert: "Failed to create the chatroom."
    end
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    photos = Array(params[:task][:photo])
    @task.photos.attach(photos) if photos.present?

    if @task.save
      redirect_to task_url(@task), notice: "Task was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tasks/1 this also marks a task a done in the database
  def update
    @task = Task.find(params[:id])

    if @task.update(task_status: "done")
      redirect_to user_path(current_user), notice: "Task has been marked as done."
    else
      redirect_to task_path(@task), alert: "Failed to mark the task as done."
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy

    redirect_to tasks_url, notice: "Task was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :description, :price, :category_id, :start_time, :location, photos: [])
  end
end

app/views/tasks/_categories.html.erb
<!-- tasks/_categories.html.erb -->
<div class="category-grid-container">
  <% @categories.each do |category| %>
    <div class="grid-item">
      <%= link_to category, class: "category-link" do %>
        <% if category.photo.attached? %>
          <%= cl_image_tag(category.photo.key, class: "category-image") %>
        <% else %>
          <%= image_tag "default-category.jpg", alt: "category-default-image", class: "category-image" %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<%# New task form conatiner %>
<div class="new-task-container"
     data-controller="carousel-form"
     data-action="touchstart->carousel-form#startSwipe touchend->carousel-form#endSwipe">
  <%= simple_form_for(@task, data: { controller: 'flatpickr' }) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-slides">
      <div class="form-slide active" data-carousel-form-target="slide">
        <div class="form-inputs">
          <%= f.label :name, "Add a title for your task*" %>
          <%= f.text_field :name, required: true, class: 'form-control' %>

          <%= f.label :description, "Write a short description for what exactly you need help with*" %>
          <%= f.text_area :description, required: true, class: 'form-control' %>

          <%= f.association :category, label: "Select a category", class: 'form-control' %>
        </div>
      </div>

      <div class="form-slide" data-carousel-form-target="slide">
        <div class="form-inputs">
          <div class="file-input">
            <%= f.label :photos, "📷 Upload a photo (max. 4)", class: 'upload-photo' %>
            <%= f.file_field :photos, required: false, multiple: true, class: 'd-none' %>
          </div>

          <%= f.label :start_time, "Add a start date (starts immediately if not selected)" %>
          <%= f.text_field :start_time, required: false, data: { flatpickr_target: "startTime", min_date: Date.today.strftime('%Y-%m-%d') }, class: 'form-control' %>

          <%= f.input :location,
            input_html: { data: { address_autocomplete_target: "address" }, class: "d-none" },
            wrapper_html: { data: { controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"] } }
          %>

        </div>
      </div>

      <div class="form-slide" data-carousel-form-target="slide">
        <div class="form-inputs">
          <%= f.label :price, "Add a price (in IDR)*" %>
          <%= f.text_field :price, required: true, class: 'form-control' %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: 'form-btn' %>
        </div>
      </div>
    </div>

    <div class="indicators">
      <span class="indicator active" data-action="click->carousel-form#goToSlide" data-slide="0"></span>
      <span class="indicator" data-action="click->carousel-form#goToSlide" data-slide="1"></span>
      <span class="indicator" data-action="click->carousel-form#goToSlide" data-slide="2"></span>
    </div>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<%= link_to task, class: "task-link" do %>
  <div class="task-container">
    <div class="task-card-left">
      <ul>
        <li class="task-name"><%= task.name %></li>
        <li><i class="fa-solid fa-location-dot" style="color: #757070;"></i> <%= task.location %></li>
        <li><%= task.start_time.nil? ? 'immediately' : Date.parse(task.start_time).strftime('%d %B %Y') %></li>

        <li class="task-status"><%= task.task_status == "available" ? "open" : "" %></li>
      </ul>
    </div>

    <div class="task-card-right">
      <% if task.user.avatar.attached? %>
        <%= cl_image_tag task.user.avatar.key, class: "avatar" %>
      <% else %>
        <%= image_tag 'default-profile.jpg', class: "avatar" %>
      <% end %>
      <p><%= task.price.round(0) %> IDR</p>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<%# This renders the top container %>
<div class="top-container">
  <div class="text-center">
    <h1 class="doit mt-4">doit.</h1>
  </div>

  <div class="text-center">
    <h1 class="explore">explore</h1>
  </div>

</div>

<%# This is the search bar to filter all the tasks %>
<form action="<%= tasks_path %>" method="get">
  <div class="form-group">
    <select name="sort" id="sort" class="form-control" onchange="this.form.submit()">
      <option value="" disabled selected>FILTER</option>
      <option value="newest">Newest</option>
      <option value="oldest">Oldest</option>
      <option value="category">Category</option>
      <option value="highest_payment">Highest Payment</option>
    </select>
  </div>
</form>

<%# This renders all the tasks based on what the user is seraching for %>
<div id="tasks">
  <div class="container">
    <% if @sort_option == "category" %>
      <%= render partial: "tasks/categories" %>
    <% else %>
      <% @tasks.order(created_at: :desc).each do |task| %>
        <% if task.task_status == "available" && task.user != current_user %>
          <%= render task %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tasks/my_tasks.html.erb
<!-- my_tasks.html.erb -->

<div class="top-bar-container">
	<div class="left">
		<%= link_to user_path(current_user) do %>
			<i class="fa-solid fa-arrow-left" style="color: #0E0000;"></i>
		<% end %>
	</div>
	<div class="right">
		<h4>Task management</h4>
	</div>
</div>

<div class="my-tasks-container">

	<%# My active tasks %>
  <div class="active-tasks-section my-4">

    <% if @tasks.any? { |task| task.user == current_user && task.task_status == "available" } %>
      <select data-controller="task-dropdown" class="form-control mytasks-form-control">
        <!-- Add a default option with value="" to prompt the user to select a task -->
        <option value="">MY ACTIVE TASKS</option>
        <% @tasks.each do |task| %>
          <% if task.user == current_user && task.task_status == "available" %>
            <option value="<%= task_path(task) %>"><%= task.name %></option>
          <% end %>
        <% end %>
      </select>
    <% else %>
      <div class="text-center">
        <h3>My active tasks</h3>
        <p>Currently no active tasks.</p>
      </div>
    <% end %>

  </div>

	<%# Tasks where i have appplied for %>
	<% if @started_tasks.any? && @started_tasks.pluck(:requested_by_id).include?(current_user.id) %>
		<div class="text-center">
			<h3>Applied tasks</h3>
		</div>


		<div class="applied-container">

			<% @started_tasks.each do |task| %>

				<div class="applied-card">

					<div class="top-container">
						<% if task.user.avatar.present? %>
							<%= image_tag task.user.avatar, class: "avatar" %>
						<% else %>
							<%= image_tag 'default-profile.jpg', class: "avatar" %>
						<% end %>
						<p><%= task.user.first_name %> <%= task.user.last_name %></p>
					</div>

					<div class="bottom-container">
						<% if task.requested_by_id == current_user.id %>
							<%= link_to task, class: "name-link" do %>
								<h4><%= task.name %></h4>
								<p><%= task.description %></p>
							<% end %>

							<div class="text-center">
								<h5 class="status-text mt-2">TASK STATUS</h5>
								<p class="pb-2">
									<% if task.task_status == "requested" %>
										REQUESTED <i class="fa-regular fa-hourglass-half" style="color: #e67e22;"></i>
									<% elsif task.task_status == "in_work" %>
										ACCEPTED <i class="fa-solid fa-check" style="color: #6fd516;"></i>
									<% end %>
								</p>
							</div>
						<% end %>
					</div>

				</div>

			<% end %>

		</div>
	<% end %>

	<%# Requested Tasks %>
	<% if @requested_tasks.any? %>

		<div class="text-center">
			<h3>Applicatins</h3>
		</div>

		<div class="applications-container">

			<% @requested_tasks.each do |task| %>
				<div class="application-card">
					<% if current_user == task.user && task.task_status == "requested" %>
						<% if task.requested_by %>
						<div class="top-container">
							<% user_avatar = task.requested_by.avatar %>
							<% if user_avatar.present? %>
								<%= image_tag user_avatar, class: "avatar" %>
							<% else %>
								<%= image_tag 'default-profile.jpg', class: "avatar" %>
							<% end %>

							<%= link_to "#{task.requested_by.first_name} #{task.requested_by.last_name}", user_path(task.requested_by) %>
						</div>
							<%= link_to task do %>
								<h4><%= task.name %></h4>
								<p><%= task.description %></p>
							<% end %>

						<% if current_user == task.user %>
							<div class="button-container">
								<%= button_to "ACCEPT", accept_request_task_path(task), method: :patch, class: "accept-button" %>
								<%= button_to "DISMISS", reject_request_task_path(task), method: :patch, class: "dismiss-button" %>
							</div>
						<% end %>

					<% else %>
						<p>Requested By: N/A</p>
					<% end %>
				</div>

				<% end %>
			<% end %>

		</div>

	<% end %>

	<%# Accepted Tasks %>
	<% if @accepted_tasks.any? %>

    <div class="text-center">
			<h3>Accepted Tasks</h3>
    </div>

			<% @accepted_tasks.each do |accepted_task| %>
        <div class="accepted-card">

          <% if accepted_task.task_status == "in_work" %>

            <div class="top-container">
              <% if accepted_task.requested_by.avatar.present? %>
                <%= image_tag accepted_task.requested_by.avatar %>
              <% else %>
                <%= image_tag 'default-profile.jpg' %>
              <% end %>
              <p>
                <%= accepted_task.requested_by.first_name %>
                <%= accepted_task.requested_by.last_name %>
              </p>
            </div>


            <div class="bottom-container">
              <%= link_to accepted_task do %>
                <h5><%= accepted_task.name %></h5>
                <p>When the task has been completed and you have paid the worker mark it as done.</p>
              <% end %>
              <% if current_user == accepted_task.user %>
                <div class="text-center">
                  <%= button_to "DONE", done_task_task_path(accepted_task), method: :patch %>
                </div>
              <% end %>
            </div>

          <% end %>
        </div>

			<% end %>
	<% end %>

</div>

app/views/tasks/new.html.erb
<div class="text-center mt-5">
  <h1>⚙️CREATE A NEW TASK</h1>
</div>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<!-- app/views/tasks/show.html.erb -->
<%# Top bar container for task show page %>
<div class="top-bar-container">
  <div class="left">
    <%= link_to :back do %>
      <i class="fa-solid fa-arrow-left" style="color: #0E0000;"></i>
    <% end %>
  </div>
  <div class="right">
    <h4>Task details</h4>
  </div>
</div>

<%# I can implement later someting that the user can see the task status
somewhere %>
<%#= @task_status %>

<%# Task details container %>
<div class="show-task-container">
  <h1><%= @task.name %></h1>

  <div class="details-container">
    <div class="left">
      <ul>
        <li>
          <% if @task.user.avatar.attached? %>
            <%= cl_image_tag @task.user.avatar.key %>
          <% else %>
            <%= image_tag 'default-profile.jpg' %>
          <% end %>
        </li>
        <li><i class="fa-solid fa-location-dot" style="color: #0E0000;"></i></li>
        <li><i class="fa-regular fa-calendar" style="color: #0E0000;"></i></li>
      </ul>
    </div>
    <div class="right">
      <ul>
        <li>
          <p>Posted by</p>
          <%= link_to user_path(@task.user) do %>
            <p class="detail"><%= @task.user.first_name %></p>
          <% end %>
        </li>
        <li>
          <p>Location</p>
          <p class="detail"><%= @task.location %></p>
        </li>
        <li>
          <p>To be done</p>
          <% if @task.start_time.present? %>
            <p class="detail"><%= @task.start_time.to_date.strftime("%d.%m.%Y") %></p>
          <% else %>
            <p class="detail">immediately</p>
          <% end %>
        </li>
      </ul>
    </div>
  </div>

</div>

<%# Task price card %>
<%# The request task button gets only rendered if user is not the task owner %>
<%# Task price card %>
<div class="price-card">
  <% if @task_status == "done" %>
    <p>TASK PRICE</p>
    <h1><%= @task.price.round(0) %> IDR</h1>
    <p class="completed">The task has been completed!</p>
  <% else %>
    <p>TASK PRICE</p>
    <h1><%= @task.price.round(0) %> IDR</h1>
    <%# Only show the "Start Task" button to the appropriate users %>
    <% unless @is_own_task %>
      <% if @task_status == "available" %>
        <% if user_signed_in? %>
          <%= button_to "SEND REQUEST", start_task_task_path(@task), method: :post, class:"price-card-btn" %>
        <% else %>
          <%= button_to "SEND REQUEST", new_user_session_path, class: 'price-card-btn' %>
        <% end %>
      <% elsif @task_status == "requested" %>
        <p>Request has been sent. You can see the task status in your profile under mangage my tasks.</p>
      <% end %>
    <% end %>
  <% end %>
</div>

<hr>

<%# Contact to open a chatroom %>
<div class="contact-container">
  <% unless @is_own_task %>
    <% if @task_status == "available" || (@task_status == "requested" && @user_can_create_chatroom) %>
      <% if @task.user_can_create_chatroom(current_user) %>
        <% if user_signed_in? %>
          <%= button_to create_chatroom_task_path(@task), method: :post, class: "contact-btn" do %>
            <i class="fa-regular fa-comment-dots fa-flip-horizontal" style="color: #2196f3;"></i>
            CONTACT <%= @task.user.first_name %>
          <% end %>
        <% else %>
          <%= button_to new_user_session_path, class: 'contact-btn' do %>
            <i class="fa-regular fa-comment-dots fa-flip-horizontal" style="color: #2196f3;"></i>
            CONTACT <%= @task.user.first_name %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<%# Task description %>
<div class="details">
  <p class="detail-heading">DETAILS</p>
  <p>- <%= @task.description %></p>
  <p>- I need a worker
    <% if @task.start_time.present? %>
      at <%= @task.start_time.to_date.strftime("%d.%m.%Y") %>
    <% else %>
      immediately
    <% end %>
  </p>
</div>

<%# Task photos %>
<% if @task.photos.attached? %>
  <div class="task-photo-grid-container" data-controller="image-grid-modal">
    <% @task.photos.each do |photo| %>
      <div class="grid-item" data-action="click->image-grid-modal#openModal">
        <%= cl_image_tag photo.key, data: { src: photo.url }, "data-src": photo.url %>
      </div>
    <% end %>
  </div>
<% end %>

<hr>

<div style="width: 95%; height: 200px; margin: 0 auto 120px auto; border-radius: 16px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/tasks/task_history.html.erb
<!-- app/views/tasks/task_history.html.erb -->
<div class="top-bar-container">
  <div class="left">
    <%= link_to user_path(current_user) do %>
      <i class="fa-solid fa-arrow-left" style="color: #0E0000;"></i>
    <% end %>
  </div>
  <div class="right">
    <h4>Task history</h4>
  </div>
</div>

<%# Task history conatiner %>
<div class="history-container">
  <% if @done_tasks.any? %>
    <% has_task_history = false %>
    <% @done_tasks.each do |task| %>
      <%# This makes sure it only gets rendered in the task owner or the doer profile history %>
      <% if task.user == current_user || task.requested_by == current_user %>
        <%= link_to task_path(task) do %>
          <p class="task-name"><%= task.name %></p>
        <% end %>
        <% if task.user == current_user %>
          <!-- Displayed when you are the one who has posted the task -->
          <p>Task done by:
            <%= link_to user_path(task.requested_by) do %>
              <%= task.requested_by.first_name %> <%= task.requested_by.last_name %>
            <% end %>
          </p>
        <% elsif task.requested_by == current_user %>
          <!-- Displayed when you are the one who has done the task -->
            <p>Task posted by:
              <%= link_to user_path(task.user) do %>
                <%= task.user.first_name %> <%= task.user.last_name %>
              <% end %>
            </p>
        <% end %>

        <p>Status: <%= task.task_status %> (Completed on <%= task.updated_at.to_date.strftime("%d.%m.%Y") %>)</p>

        <% if task.user == current_user %>
          <p>You spent: <span class="text-danger"><%= task.price %> IDR</p>
        <% elsif task.requested_by == current_user %>
          <p>You earned: <span class="text-success"><%= task.price %></span> IDR</p>
        <% end %>
        <hr>

        <% has_task_history = true %>
        <!-- Add any additional information you want to display for each task -->
      <% end %>
    <% end %>
    <% unless has_task_history %>
      <div class="text-center">
        <p>No task history available.</p>
      </div>
    <% end %>
  <% else %>
    <div class="text-center">
      <p>No task history available.</p>
    </div>
  <% end %>
</div>