config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home" # landing page (root_path)
  devise_for :users

  resources :users, only: [:show]
  resources :tasks do
    member do
      post 'start_task'
      patch 'accept_request'
      patch 'reject_request'
      patch 'done_task'
      post 'create_chatroom'
    end
    collection do
      get 'my_tasks' # Route for "my_tasks"
      get 'task_history', to: 'tasks#task_history' # Route for "task_history"
    end
  end

  resources :categories
  resources :chatrooms, only: [:index, :show, :new, :create] do
    resources :messages, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy
  has_many :notifications, as: :recipient, dependent: :destroy # Notifications that the user received
  has_one_attached :avatar
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
    @created_tasks = @user.tasks
    @requested_tasks = Task.where(task_status: "requested", user: @user)
    @accepted_tasks = Task.joins(:user).where(users: { id: @user.id }, task_status: "in_work")
    @started_tasks = Task.where("(task_status = 'requested' AND requested_by_id = :user_id) OR task_status = 'in_work'", user_id: @user.id)
    @done_tasks = Task.where(task_status: "done", user: @user).or(Task.where(task_status: "done", requested_by: @user))
    @task = Task.find_by(requested_by: current_user)

    @earned_money = @done_tasks.where(requested_by: current_user).sum(:price) # shows the earned money in the profile
    @spent_money = current_user.tasks.where(task_status: 'done').sum(:price) # shows the spent money in the profile
    # This is needed for the blue dot in the navbar if there is a new message
    @chatrooms = Chatroom.joins(task: :user)
                         .joins("LEFT JOIN messages ON messages.chatroom_id = chatrooms.id")
                         .where("(tasks.user_id = :current_user_id OR chatrooms.user_id = :current_user_id)", current_user_id: current_user.id)
                         .group("chatrooms.id")
                         .order("MAX(messages.created_at) DESC NULLS LAST")
  end

  # Method to create a new user
  def create
    @user = User.new(sign_up_params)
    if @user.save
      # Handle successful user creation
      redirect_to @user
    else
      # Handle validation errors
      render 'new'
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation,
      :avatar,
      :zip_code,
      :street_name,
      :house_number
    )
  end
end

app/views/users/show.html.erb
<%# app/views/users/show.html.erb %>

<%# User top conatiner %>
<div class="user-top-container">
  <div class="user-overview-container">
    <div class="profile-picture-container">
      <% if @user.avatar.attached? %>
        <%= cl_image_tag @user.avatar.key, class: "avatar" %>
      <% else %>
        <%= image_tag 'default-profile.jpg', class: "avatar" %>
      <% end %>
    </div>
    <div class="user-profile-info">
      <h4><%= @user.first_name %></h4>
      <h4><%= @user.last_name %></h4>
      <% if user_signed_in? && current_user == @user %>
        <%= link_to edit_user_registration_path do %>
          <i class="fa-regular fa-pen-to-square" style="color: #0E0000;"></i>
        <% end %>
        <p><%= @user.email %></p>
        <p><%= @user.zip_code %></p>
        <p><%= @user.street_name %> <%= @user.house_number %></p>
      <% end %>
    </div>
    </div>
    <div class="style-element-container">
    </div>
</div>

<%# User accout overview %>
<div class="profile-account-overview">
  <% if user_signed_in? && current_user == @user %>
    <p><span class="text-overline">ACCOUNT</span> <span class="text-underline">OVERVIEW</span></p>

    <%# In the money container I implemented animated numbers but only if the value is not 0.
    If the value is 0, I display the static value without the animated-number controller.
    This is because the animated-number controller does not work with 0 values.  %>
    <div class="money-container">
      <div class="money-left">
        <p class="money-text">EARNED MONEY</p>
        <% if @earned_money.round(0) == 0 %>
          <!-- If @earned_money.round(0) is 0, display the static value without the animated-number controller -->
          <p class="money-plus"><%= @earned_money.round(0) %></p>
        <% else %>
          <!-- If @earned_money.round(0) is not 0, include the animated-number controller -->
          <p class="money-plus" data-controller="animated-number" data-animated-number-start-value="0" data-animated-number-end-value="<%= @earned_money.round(0) %>" data-animated-number-duration-value="3000">
            <%= @earned_money.round(0) %>
          </p>
        <% end %>
      </div>
      <div class="money-right">
        <p class="money-text">SPENT MONEY</p>
        <% if @spent_money.round(0) == 0 %>
          <!-- If @spent_money.round(0) is 0, display the static value without the animated-number controller -->
          <p class="money-minus"><%= @spent_money.round(0) %></p>
        <% else %>
          <!-- If @spent_money.round(0) is not 0, include the animated-number controller -->
          <p class="money-minus" data-controller="animated-number" data-animated-number-start-value="0" data-animated-number-end-value="<%= @spent_money.round(0) %>" data-animated-number-duration-value="3000">
            <%= @spent_money.round(0) %>
          </p>
        <% end %>
      </div>
    </div>

    <ul>
      <%= link_to my_tasks_tasks_path do %>
        <li>
          <div class="left-content">
            <i class="fa-solid fa-list-check" style="color: #0E0000;"></i>
            <p>MANAGE MY TASKS</p>
          </div>
            <i class="fa-solid fa-angle-right" style="color: #0E0000;"></i>
        </li>
      <% end %>
      <%= link_to task_history_tasks_path do %>
        <li>
          <div class="left-content">
            <i class="fa-solid fa-clock-rotate-left" style="color: #0E0000"></i>
            <p>TASK HISTORY</p>
          </div>
          <i class="fa-solid fa-angle-right" style="color: #0E0000;"></i>
        </li>
      <% end %>
      <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
        <li>
          <div class="left-content">
            <i class="fa-solid fa-lock" style="color: #0E0000;"></i>
            <p>LOG OUT</p>
          </div>
            <i class="fa-solid fa-angle-right" style="color: #0E0000;"></i>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

<%# If the current user is on a different user's profile page, show the tasks of that user that are currently available. %>
<div class="container">
  <% if user_signed_in? && current_user != @user %>
    <% if @user.tasks.any? %>
      <h3 class="text-center"><%= @user.first_name.upcase %>'S ACTIVE TASKS</h3>
      <ul>
        <% @user.tasks.each do |task| %>
          <% if task.task_status == "available" && task.user != current_user %>
            <%= link_to task do %>
              <%= render task %>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <div class="text-center">
        <p><%= @user.first_name %> has no active tasks posted at the moment.</p>
      </div>
    <% end %>
  <% end %>
</div>


<%# This checks that only the users with the email simon@gmail.com can add a new category %>
<% if user_signed_in? && current_user.email == "simon@gmail.com" && current_user == @user %>
  <div class="text-center">
    <%= link_to "Add new category", new_category_path, class: "btn btn-primary shadow" %>
  </div>
<% end %>