config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home" # landing page (root_path)
  devise_for :users

  resources :users, only: [:show]
  resources :tasks do
    member do
      post 'start_task'
      patch 'accept_request'
      patch 'reject_request'
      patch 'done_task'
      post 'create_chatroom'
    end
    collection do
      get 'my_tasks' # Route for "my_tasks"
      get 'task_history', to: 'tasks#task_history' # Route for "task_history"
    end
  end

  resources :categories
  resources :chatrooms, only: [:index, :show, :new, :create] do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% flash.each do |type, msg| %>
  <div id="alert" class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("doit-icon-default.jpeg", alt: "doit icon") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Add new task", new_task_path, class: "nav-link" %>
          </li>
          <%# Savety check that only the user with the email 'simon@gmail.com'
            can add a new category %>
          <li>
            <% if user_signed_in? && current_user.email == 'simon@gmail.com' %>
              <%= link_to "Add new category", new_category_path, class: "nav-link" %>
            <% end %>
          </li>
          <li>
            <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_desktop.html.erb
<%# Desktop Navbar %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%#= image_tag("doit-icon-default.jpeg", alt: "doit icon") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Add new task", new_task_path, class: "nav-link" %>
          </li>
          <%# Savety check that only the user with the email 'simon@gmail.com'
            can add a new category %>
          <li>
            <% if user_signed_in? && current_user.email == 'simon@gmail.com' %>
              <%= link_to "Add new category", new_category_path, class: "nav-link" %>
            <% end %>
          </li>
          <li>
            <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_mobile.html.erb
<%# Mobile Navbar %>
<div class="mobile-nav-container">
  <%= link_to root_path, class: "navbar-item-container" do %>
    <div class="item">
      <%= image_tag("home-icon.png", alt: "home icon") %>
      <p>Home</p>
    </div>
  <% end %>
  <%= link_to tasks_path, class: "navbar-item-container" do %>
    <div class="item">
      <%= image_tag("search-icon.png", alt: "search icon") %>
      <p>Search</p>
    </div>
  <% end %>
  <%= link_to new_task_path, class: "navbar-item-container larger-image" do %>
    <div class="item">
      <%= image_tag("plus-icon.png", alt: "plus icon") %>
      <p>Create</p>
    </div>
  <% end %>
  <%= link_to chatrooms_path, class: "navbar-item-container" do %>
    <div class="item">
      <%= image_tag("message-icon.png", alt: "message icon") %>
      <% if @chatrooms&.any? { |chatroom| chatroom.unread_messages?(current_user) } %>
        <span class="notification-dot"></span> <!-- Blue notification dot -->
      <% end %>
      <p>Messages</p>
    </div>
  <% end %>
  <%= link_to (user_signed_in? ? user_path(current_user) : new_user_session_path), class: "navbar-item-container" do %>
    <div class="item">
      <%= image_tag("profile-icon.png", alt: "profile icon") %>
      <p>Profile</p>
    </div>
  <% end %>
</div>

app/views/shared/_pwa_instruction.erb
<div class="pwa-container">
  <div class="pwa-content">
  <h1>WELCOME TO DOIT</h1>
  <h5>Get everything done instantly. The doit. app connects local freelancers and professionals with help-seeking people around them instantly.</h5>
  <p class="mt-5">To use the app you have to:</p>
  <h6>OPEN THE APP IN YOU PHONES BRWOSER</h6>
  <%= image_tag "pwa_instruction_1.jpg", alt: "pwa instruction image", class: "pwa-img-1" %>
  <h6>CLICK ON THE BROWSER MENU AND SELCET "ADD TO HOME SCREEN"</h6>
  <%= image_tag "pwa_instruction_2.jpg", alt: "pwa instruction image", class: "pwa-img-2" %>
  </div>
</div>