config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home" # landing page (root_path)
  devise_for :users

  resources :users, only: [:show]
  resources :tasks do
    member do
      post 'start_task'
      patch 'accept_request'
      patch 'reject_request'
      patch 'done_task'
      post 'create_chatroom'
    end
    collection do
      get 'my_tasks' # Route for "my_tasks"
      get 'task_history', to: 'tasks#task_history' # Route for "task_history"
    end
  end

  resources :categories
  resources :chatrooms, only: [:index, :show, :new, :create] do
    resources :messages, only: :create
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories
  def index
    @categories = Category.all.order(:name)
  end

  # GET /categories/1
  def show
    @tasks = @category.tasks
    @category = Category.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :description, :photo)
  end
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name,
                required: true %>
    <%= f.input :description,
                required: true %>
    <%= f.input :photo,
                required: false,
                label: "Category photo" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/_task.html.erb
<%= link_to task, class: "task-link" do %>
  <div class="task-container">
    <div class="task-card-left">
      <ul>
        <li class="task-name"><%= task.name %></li>
        <li><i class="fa-solid fa-location-dot" style="color: #757070;"></i> <%= task.location %></li>
        <li><i class="fa-regular fa-calendar" style="color: #757070;"></i> <%= task.start_time.nil? ? 'immediately' : DateTime.parse(task.start_time).strftime('%a. %d. %B') %></li>
        <li class="task-status"><%= task.task_status == "available" ? "open" : "" %></li>
      </ul>
    </div>

    <div class="task-card-right">
      <% if task.user.avatar.attached? %>
        <%= cl_image_tag task.user.avatar.key, class: "avatar" %>
      <% else %>
        <%= image_tag 'default-profile.jpg', class: "avatar" %>
      <% end %>
      <p><%= task.price.round(0) %> IDR</p>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<%# Categories Index Page %>
<%# This renders the top container %>
<div class="top-container">
  <div class="text-center">
    <h1 class="doit mt-4">doit.</h1>
  </div>

  <div class="text-center">
    <h1 class="explore">explore</h1>
  </div>

</div>

<%# This renders the categories in a grid %>
<div class="grid-container">
  <% @categories.each do |category| %>
    <div class="grid-item">
      <%= link_to category, class: "category-link" do %>
        <% if category.photo.attached? %>
          <%= cl_image_tag(category.photo.key, class: "category-image") %>
        <% else %>
          <%= image_tag "default-category.jpg", alt: "category-default-image", class: "category-image" %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<%# Top bar container for category show page %>
<div class="top-bar-container">
  <div class="left">
    <%= link_to categories_path do %>
      <i class="fa-solid fa-arrow-left" style="color: #0E0000;"></i>
    <% end %>
  </div>
  <div class="right">
    <h4>Category <%= @category.name %></h4>
  </div>
</div>
<div class="category-description">
  <h6><%= @category.description %></h6>
</div>





<%# This renders only the tasks that are available and not from the
user that is currently logged in %>
<div class="container">
  <% @tasks.each do |task| %>
    <% if task.task_status == "available" && task.user != current_user %>
      <%= render task %>
    <% end %>
  <% end %>
</div>



<%# Savety check that only the user with the email 'simon@gmail.com'
can edit and delete the category %>

<% if user_signed_in? && current_user.email == 'simon@gmail.com' %>
  <div class="container">
    <%= link_to "Edit this category", edit_category_path(@category) %> |
    <%= button_to "Destroy this category", @category, method: :delete %>
  </div>
<% end %>